name: DevSecOps Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: echo "Tests would run here"

      - name: Static Code Analysis
        run: echo "Run Semgrep or Bandit here"

      - name: Build Docker Image
        run: echo "docker build -t myapp ."

      - name: Scan Docker Image
        run: echo "Run Trivy to scan for CVEs"
